config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  post 'simple_pages/thank_you'

  post 'payments/create'

  root 'simple_pages#landing_page'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogAccessoiresBerlin</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <% if alert %>
      <div class="alert alert-warning" role="alert"><%= alert %></div>
    <% end %>
    <% if notice %>
      <div class="alert alert-warning" role="alert"><%= flash[:notice] %></div>
    <% end %>

    <nav class="navbar navbar-inverse navbar-fixed top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="input-group">
            <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
              <div class="input-group">
              <%= form.text_field :q, id: 'q', value: params[:q], class: 'form-control', placeholder: 'Search for...' %>
              <span class="input-group-btn">
              <%= form.submit 'Search', class: 'btn btn-default', id: 'search-button' %>
              </span>
            </div>
            <% end %>
          </div><!--end search-form-->
        </div><!--end navbar-header-->
        <div class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">
            <li role="presentation"><%= link_to "Home", root_path %></li>
            <li role="presentation"><%= link_to "About", simple_pages_about_path %></li>
            <li role="presentation"><%= link_to "Products", products_path %></li>
            <% if signed_in? && current_user.admin? %>
              <li role="presentation"><%= link_to "Orders", orders_path %></li>
            <% end %>
            <li role="presentation"><%= link_to "User", users_path %></li>
            <li role="presentation"><%= link_to "Contact", simple_pages_contact_path %></li>
            <li role="presentation">
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
            </li>
          </ul>
        </div><!--end nav-->
      </div><!--end nav container-->
    </nav><!--end navbar-->




    <%= yield %>


  </body>



  <footer>
    <div class="copyright">
      <p>&copy; 2017 DK</p>
    </div><!--end copyright-->
  </footer>

</html>